BEGIN;

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('Software developer CV template', 'https://www.fish4.co.uk/career-advice/software-developer-cv-template-2/', 'If you are looking to apply for a range of software developer roles, we can help get your CV ready with our software developer CV template. Simply download our template and follow the examples provided', 'others', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='other'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='contacts in industry'), 'indirect');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('15 Female Web Developers To Follow On Instagram', 'https://blog.vanila.io/15-female-web-developers-to-follow-on-instagram-15d7927824e5', 'One of the best ways to get your motivation to work is to connect on social media with people of same passion. If you are interested in the web or mobile development, you will find these girls and their work very inspiring. Follow these 15 female web developers on Instagram for daily inspiration, good advice, and coding tips & tricks.', 'article', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='contacts in industry'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'direct');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('3 Entrepreneurs Share Advice for Women in Tech', 'https://www.startupinstitute.com/blog/2016-08-23-entrepreneurs-advice-women-in-tech', 'In 2011, the Level Playing Field Institute published a study that revealed women in tech (especially women of color) had more negative work experiences than their male counterparts, which in turn led to high turnover rates and contributed to job dissatisfaction overall. Women in tech, according to the numbers, are in the shadow of men; women make up a mere 11% of executives at Fortune 500 companies and only 5% of startups are owned by women. In search of inspiration, I spoke with three female influencers from Startup Institute''s community, all of whom are founders, to hear more about their experiences being a motivating force in this up-and-coming ecosystem.', 'article', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='contacts in industry'), 'indirect');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('15 Women Web Designers Who Made A Mark In 2018 ', 'https://www.designhill.com/design-blog/top-women-web-designers-made-mark/', 'While men dominate the world of web design, their Women counterparts too are gradually making their presence felt. In fact, we can now list women web designers who are known for high quality standards of web designing. They are rated higher for creativity, innovation, new ideas and techniques of designing websites. So, we decided to prepare an article featuring top 15 women web designers giving their expert advice for young web designers.', 'article', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'direct');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('Women in tech: from flight attendant to web developer', 'https://blog.learningpeople.co.uk/women-in-tech-from-flight-attendant-to-web-developer', 'If there is one sure fire way to motivate a woman who dreams of a career in tech it is reading about other inspiring women who are paving the way. So, if you are an aspiring coding newbie stuck in a yawn-inducing job and dreaming of a career change, then we have got a treat for you.', 'article', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='other'), 'indirect');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('Inclusive Boards', 'http://www.inclusiveboards.co.uk/diversity-in-tech-landscape/', 'As part of Inclusive Boards increasing work within the UK Tech sector we are releasing a briefing about the current landscape. We have found that there is a distinct lack of available data in regards to BAME diversity in tech. Whilst data in relation to gender diversity in tech is more readily available, the figures and experiences make for depressing reading. [more]', 'article', NULL, NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='ethnicity'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='other'), 'indirect');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('Is “Culture Fit” Eliminating Your Best Tech Candidates?', 'https://www.creativequills.co.uk/is-culture-fit-eliminating-your-best-tech-candidates/', '[cultural bias in the tech industry]', 'article', 'UK', NULL) returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='other'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='age'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='ethnicity'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='disability'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='mental health'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='caring responsibilities'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='socioeconomic'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='sexuality'), 'indirect');

with insert1 as (insert into resource (resource_name, url, resource_description, resource_type, country, city) values ('ACHIEVING DIVERSITY IN THE TECHNOLOGY INDUSTRY', 'http://www.achievingdiversityin.tech/', 'A monthly meetup to discuss improving diversity in the technology industry', 'meetup', 'UK', 'London') returning resource_id) insert into demographic_resource_link (link_resource_id, link_demographic_tag_id, relevance) values ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='other'), 'direct'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='age'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='ethnicity'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='disability'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='mental health'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='caring responsibilities'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='education'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='socioeconomic'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='gender'), 'indirect'), ((select * from insert1), (select demographic_tag_id from demographic_tag where tag_name='sexuality'), 'indirect');

COMMIT;